import { PatternCardProps } from "@/app/components/PatternCard/types"
import { Apple, BicepsFlexed, BowArrow, Briefcase, Cake, CircleDotDashed, ClockFading, Coffee, Cog, Dog, FishSymbol, FlaskConical, Hand, Handshake, Plane, Pointer, Rainbow, Sparkle } from "lucide-react"

export const deck: PatternCardProps[] = [
    {
        id: 1,
        name: "Abstract Factory",
        image: "/abstract-factory.png",
        description: "",
        icon: Cog,
    },
    {
        id: 2,
        name: "Builder",
        image: "/builder.png",
        description: "",
        icon: Cake,
    },
    {
        id: 3,
        name: "Factory Method",
        image: "/factory-method.png",
        description: "",
        icon: Dog,
    },
    {
        id: 4,
        name: "Prototype",
        image: "/prototype.png",
        description: "",
        icon: Sparkle,
    },
    {
        id: 5,
        name: "Singleton",
        image: "/singleton.png",
        description: "",
        icon: FlaskConical,
    },
    {
        id: 6,
        name: "Adapter",
        image: "/adapter.png",
        description: "",
        icon: BicepsFlexed,
    },
    {
        id: 7,
        name: "Bridge",
        image: "/bridge.png",
        description: "",
        icon: Rainbow,
    },
    {
        id: 8,
        name: "Composite",
        image: "/composite.png",
        description: "",
        icon: Apple,
    },
    {
        id: 9,
        name: "Decorator",
        image: "/decorator.png",
        description: "",
        icon: Coffee,
    },
    {
        id: 10,
        name: "Facade",
        image: "/facade.png",
        description: "",
        icon: Plane,
    },
    {
        id: 11,
        name: "Flyweight",
        image: "/flyweight.png",
        description: "",
        icon: FishSymbol,
    },
    {
        id: 12,
        name: "Proxy",
        image: "/proxy.png",
        description: "",
        icon: Hand,
    },
    {
        id: 13,
        name: "Chain of Responsibility",
        image: "/chain-of-responsibility.png",
        description: "",
        icon: BowArrow,
    },
    {
        id: 14,
        name: "Command",
        image: "/command.png",
        description: "",
        icon: Pointer,
    },
    {
        id: 15,
        name: "Interpreter",
        image: "/interpreter.png",
        description: "",
        icon: CircleDotDashed,
    },
    {
        id: 16,
        name: "Iterator",
        image: "/iterator.png",
        description: "",
        icon: Briefcase,
    },
    {
        id: 17,
        name: "Mediator",
        image: "/mediator.png",
        description: "",
        icon: Handshake,
    },
    {
        id: 18,
        name: "Memento",
        image: "/memento.png",
        description: "",
        icon: ClockFading,
    },
]